### ISSUE TITLE
DATA STRUCTURE

### ISSUE THREAD

**Issue by Tim-BinCoding** [PNC-NODE-PROJECT/G02-NODE-PROJECT#2]

**Comment by Tim-BinCoding** [comment]
![Uploading Data structure.png…]()

**Comment by Tim-BinCoding** [comment]
![Data structure](https://user-images.githubusercontent.com/93531404/165299607-64392537-be39-4083-bddd-6ed95c7300b3.png)

**Comment by harrahx3** [comment]
- I'm still not clear about "isHost"
- also the structure for "Answers" is not clear
- If you use MongoDB maybe you can drop your Schema also

**Comment by Tim-BinCoding** [comment]
![Data structure](https://user-images.githubusercontent.com/93531404/165747630-b9dc9815-2aad-49e7-ab87-a6121291068b.png)
